# Generated by Django 5.1.7 on 2025-04-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_data_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='funfact',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
