# Generated by Django 5.1.7 on 2025-04-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_data_funfact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='video',
            field=models.CharField(max_length=200),
        ),
    ]
