# Generated by Django 5.1.7 on 2025-04-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_data_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
